# Generated by Django 3.0.7 on 2020-10-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_fsm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSoftDelete',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('custom_active', models.BooleanField(default=True)),
                ('other_field', models.TextField()),
            ],
        ),
    ]
