# Generated by Django 3.2.3 on 2022-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_customsoftdelete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleFromAbstractModel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
