# Generated by Django 4.1 on 2022-08-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_customtablename'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTriggerProxy',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tests.testtrigger',),
        ),
    ]
