# Generated by Django 4.2.6 on 2024-03-06 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0013_alter_testtrigger_m2m_field_changedcondition"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedTestModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("char_field", models.CharField(max_length=128, null=True)),
                (
                    "test_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tests.testmodel"
                    ),
                ),
            ],
        ),
    ]
